### PR TITLE
add github workflows

### LINKED ISSUE #20: Any plan to use Github Actions
Hey, I was wondering if you have any plans to migrate to github actions.

If this is something you would like, I am more than happy to help with it.

Thanks.

### PR DESCRIPTION
**Pull request by zaherg**
This PR should close #20 in case it was merged.

The result of the tests can be seen here https://github.com/linuxjuggler/laravel-code-style/actions/runs/45106890

### CODE REVIEW

**Comment by owenvoke** [comment]
You can use `actions/checkout@v2`. :+1:

**Comment by zaherg** [comment]
done

**Comment by matt-allan** [comment]
Thanks for this!

I just remembered we were using scheduled builds with Travis (#12). It [looks like it's possible to do this with Github Actions too](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule).

**Comment by zaherg** [comment]
Sure we can do that too, I'll push the changes soon

**Comment by zaherg** [comment]
done

**Comment by matt-allan** [comment]
Thanks!

**Pull request merged**
