### PR TITLE
ci: update to test PHP 8

### PR DESCRIPTION
**Pull request by owenvoke**
This updates to test against PHP 8 in CI.

### CODE REVIEW

**Comment by matt-allan** [comment]
Thanks! The test failure is because of #47, we can probably skip that for now.

**Comment by owenvoke** [comment]
@matt-allan, do you want me to skip that somewhere?

**Comment by matt-allan** [comment]
@owenvoke if you could add `$this->markTestSkipped('waiting on upstream')` or something along those lines to the failing test for now that would be great. It keeps failing the cron job and sending me emails that I cant do anything about right now 😁

**Comment by owenvoke** [comment]
Ah, sorry about that! I've disabled email notifications just for that reason. 😬 I'll skip the test for now.

Edit: Should be skipping now. 👍🏻

**Pull request merged**
