### PR TITLE
Add support for Laravel 8

### PR DESCRIPTION
**Pull request by mfn**
## Summary
- Add support for Laravel 8
- composer: allow installing dev dependencies, but prefer stable
- add orchestra/testbench
- add test for publishing :muscle:
- expand github actions test matrix to test against actual Laravel versions

### CODE REVIEW

**Comment by mfn** [comment]
Oh wow, why does the test suite take ~3m for 3 tests 🤔

Tests are green, but the test matrix doesn't include Laravel versions it's (likely) only the latest 7.x stable release. Interestingly, I didn't see the actual package illuminate/support installed on the GHA log…

I tested it locally by just using `^8.0` with minimum-stability=dev and the tests are green, though I'm not sure they actually do test the integration.

I guess will know once 8.0 is released 🤷‍♀️

**Comment by matt-allan** [comment]
Hi, thanks for the PR.

The test is slow because it just runs php-cs-fixer on the entire Laravel codebase and ensures it matches.

There isn't a test for the integration right now. It hopefully won't break because it's just one method call but PRs are welcome to add one. I don't think there's an easy way to test package publishing with orchestra/testbench though.

**Comment by mfn** [comment]
> The test is slow because it just runs php-cs-fixer on the entire Laravel codebase and ensures it matches.

Hah, nice one 👍 


> I don't think there's an easy way to test package publishing with orchestra/testbench though.

Don't know about publishing, but for a start it's possible to "boot" the service provider. This would already ensure it's compatible with the new Laravel version (e.g. interface changes, etc…)

Orchestra supports this via `getPackageProviders`, see e.g. https://github.com/barryvdh/laravel-ide-helper/blob/1ca875fbca9fdae4d3eedc98aa4463d3ab568ecd/tests/Console/ModelsCommand/AbstractModelsCommand.php#L29-L32

I can take a look later if no one beats me to it.

**Comment by mfn** [comment]
@matt-allan all and more done, PR description updated!

**Comment by matt-allan** [comment]
This looks great, thanks so much @mfn!

**Comment by mfn** [comment]
Thanks!

That was close, one more day to go for the great event 😼

**Pull request merged**
