### PR TITLE
Switch to alpha ordered imports

### PR DESCRIPTION
**Pull request by lhsazevedo**
Laravel [is now using](https://github.com/laravel/framework/pull/29933) alphabetically ordered imports.

### CODE REVIEW

**Comment by HDVinnie** [comment]
Not a fan. 100% preffered length ordering!

**Comment by lhsazevedo** [comment]
It's not that pretty but I find it way more readable.

You can [override the rule](https://github.com/matt-allan/laravel-code-style/blob/master/README.md#rules) easily.

**Comment by lhsazevedo** [comment]
For some reason, 7.2 Travis build with `COMPOSER_FLAGS="--prefer-stable --prefer-lowest"` var is failing.

**Comment by matt-allan** [comment]
I think the `laravel/framework` dependency probably needs to be locked to `1bbe5528568555d597582fdbec73e31f8a818dbc` as the minimum revision constraint. Otherwise the tests will install a version that uses alpha ordered imports and fail. For example, `"dev-master#1bbe552"` should work.

**Comment by lhsazevedo** [comment]
Can we constrain to ^[6.0.3](https://github.com/laravel/framework/releases/tag/v6.0.3)? This release merges the new ordering.

**Comment by matt-allan** [comment]
@lhsazevedo yeah, if there is a stable release that would be better.

**Comment by lhsazevedo** [comment]
🚀

**Comment by matt-allan** [comment]
Thanks!

**Pull request merged**
